2023-04-19 02:32:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.prepareLocal(Session.java:550)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-19 03:27:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.prepareLocal(Session.java:550)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 17:45:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Session.getTransaction(Session.java:1623)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1633)
	at org.h2.engine.Session.setSavepoint(Session.java:812)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcConnection.commit(JdbcConnection.java:479)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:169)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 18:47:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.prepareLocal(Session.java:550)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 18:51:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.prepareLocal(Session.java:550)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 18:52:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.prepareLocal(Session.java:550)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 18:52:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.prepareLocal(Session.java:550)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 18:52:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Session.getTransaction(Session.java:1623)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1633)
	at org.h2.engine.Session.setSavepoint(Session.java:812)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:193)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 18:55:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Session.getTransaction(Session.java:1623)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1633)
	at org.h2.engine.Session.setSavepoint(Session.java:812)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:193)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 18:56:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Session.getTransaction(Session.java:1623)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1633)
	at org.h2.engine.Session.setSavepoint(Session.java:812)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcConnection.commit(JdbcConnection.java:479)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:169)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 18:59:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.prepareLocal(Session.java:550)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 19:06:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Session.getTransaction(Session.java:1623)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1633)
	at org.h2.engine.Session.setSavepoint(Session.java:812)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcConnection.commit(JdbcConnection.java:479)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:169)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 19:08:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Session.getTransaction(Session.java:1623)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1633)
	at org.h2.engine.Session.setSavepoint(Session.java:812)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:193)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 19:08:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.prepareLocal(Session.java:550)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 19:12:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Session.getTransaction(Session.java:1623)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1633)
	at org.h2.engine.Session.setSavepoint(Session.java:812)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:193)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 19:12:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Session.getTransaction(Session.java:1623)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1633)
	at org.h2.engine.Session.setSavepoint(Session.java:812)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:193)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 19:13:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Session.getTransaction(Session.java:1623)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1633)
	at org.h2.engine.Session.setSavepoint(Session.java:812)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:193)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at com.se.rdc.core.utils.H2DbHandler.close(H2DbHandler.java:171)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:377)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-04-20 19:13:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Session.getTransaction(Session.java:1623)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1633)
	at org.h2.engine.Session.setSavepoint(Session.java:812)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:164)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:150)
	at com.se.rdc.core.utils.H2DbHandler.executeUpdate(H2DbHandler.java:95)
	at com.se.rdc.core.utils.H2KeyPairDbStore.removeExpired(H2KeyPairDbStore.java:121)
	at com.se.rdc.core.utils.CachedDbObject.closeDbStore(CachedDbObject.java:376)
	at com.se.rdc.core.utils.CachedDbObject.access$000(CachedDbObject.java:18)
	at com.se.rdc.core.utils.CachedDbObject$1.run(CachedDbObject.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
